### ISSUE TITLE
Treat `parallel` like `describe` to support mocha.parall syntax

### ISSUE THREAD

**Issue by stefanbuck** [lo1tuma/eslint-plugin-mocha#125]
To run some of our tests in parallel, we recently switched to [mocha.paralle](https://github.com/danielstjules/mocha.parallel). This causes issues with the rule `no-top-level-hooks`, because we had to replaced `describe()` with `parallel()`. 

Do you think, it makes sense to add support for `mocha.paralle`? Would you accept a PR for that?

**Comment by josephfrazier** [comment]
One workaround is to simply import `mocha.parallel` as `describe` rather than `parallel`. That way, the linter thinks that it's just the normal `describe` function. However, this can be confusing, and it makes it hard/impossible to have parallel tests and serial tests in the same file.

**Comment by stefanbuck** [comment]
Smart idea, didn't think about this. Anyway, I would work on a PR if the @lo1tuma accepts it.

**Comment by lo1tuma** [comment]
Sounds reasonable to me.
We could introduce a new shared [setting](https://github.com/lo1tuma/eslint-plugin-mocha/blob/86684eb283cfac359c423df2c12d6f4322f92b06/lib/util/settings.js) for this and extend [`isDescribe`](https://github.com/lo1tuma/eslint-plugin-mocha/blob/86684eb283cfac359c423df2c12d6f4322f92b06/lib/util/ast.js#L24) to also accept additional suite function names as second argument.

**Comment by stefanbuck** [comment]
Just to confirm, with shared setting you mean a new rule like `mocha/no-paralle-tests`, right?

**Comment by lo1tuma** [comment]
No, I’m not talking about creating a new rule. Shared settings is way to reuse a specific setting in multiple rules. It is [described in the official ESLint documentation](http://eslint.org/docs/user-guide/configuring#adding-shared-settings).
Currently some rules in this plugin already make use of two shared settings: `mocha/additionalTestFunctions` and `mocha/additionalXFunctions`.
Providing a way to configure additional suite function names would probably make sense for more rules than just `no-top-level-hooks`, that’s why I suggested to make this a shared setting instead of a rule option.

**Comment by lo1tuma** [comment]
Fixed by #126.
