### ISSUE TITLE
no-skipped-tests should not be autofixable

### ISSUE THREAD

**Issue by robinclaes** [lo1tuma/eslint-plugin-mocha#242]
Hi all, 

The no-skipped-tests autofix replaces `it.skip()` with `it()`

In my opinion, this should not happen as this actually alters the way tests are run.
The rule is definitely valid, but I suggest not making this autofixable.

What do you guys think? I'd be happy to submit a PR.

**Comment by lo1tuma** [comment]
Personally I don’t have a strong opinion on that since I never use skipped tests. We already decided a while ago to remove the autofix feature from `no-exclusive-tests` because editors or IDEs automatically apply autofixes all the time and it becomes annoying when you want to run only one test from your IDE.
