### ISSUE TITLE
Drop node 0.10 and iojs support

### ISSUE THREAD

**Issue by lo1tuma** [lo1tuma/eslint-plugin-mocha#47]
With the next major version we should consider to stop supporting node 0.10 and iojs officially.

**Comment by lxanders** [comment]
Do you know of a way to find out on which versions of node this plugin was used? I don't think there is one. Anyway I think you are right - thinking about people who will stop using this plugin because they don't want to update der node: I guess most people who don't update their node at all since such a long time will most likely not have a problem using the old version of this plugin a while longer. So I'm all in for this change.
